### ISSUE TITLE
I dont see the copy of the email saved in my sent box. 

### ISSUE THREAD

**Issue by jpca999** [dwyl/sendemail#113]
How can i achive it ?

**Comment by nelsonic** [comment]
@jpca999 you're going to need to give us a bit more detail. 💭 
What email sending service provider are you using? 🤷‍♂️

**Comment by jpca999** [comment]
When I send the email I want to have a copy of the sent email in my sent mailbox.   
Just like a normal email. 
Is there a way to achieve that?

**Comment by nelsonic** [comment]
I don't think AWS SES has the concept of a "sent" mailbox the way GMail does.
Hence me asking what service provider you are using.
You could just use the `bccAddresses` to send yourself a copy of every email and they have a full history.

**Comment by jpca999** [comment]
// HEre is the code that actually works. 


let nodemailer = require('nodemailer');
let AWS = require('aws-sdk');

// configure AWS SDK
AWS.config.update({
  accessKeyId: "CHANGE-ITAKCHANGEIWM4VSNG3O6G",
  secretAccessKey: "+CHANGE-ITAKCHANGEIWM4VSNG3O6G,
  region: "us-east-2",
});

// create Nodemailer SES transporter
let transporter = nodemailer.createTransport({
SES: new AWS.SES({
  apiVersion: '2010-12-01'
})
});

// send some mail
transporter.sendMail({
  from: 'the@email.com',
  to: 'the@email.com,
  subject: 'Message',
  text: 'I hope this message gets sent!'
}, (err, info) => {
  console.log(info.envelope);
  console.log(info.messageId);
});

**Comment by nelsonic** [comment]
https://youtu.be/79DijItQXMM
