### ISSUE TITLE
SendGrid still 12k free per month 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/sendemail#17]
https://sendgrid.com/pricing
![sendgrid-12k-free](https://cloud.githubusercontent.com/assets/194400/10602488/76fb7518-7710-11e5-87f3-2eef6a6eb2e7.png)

**Comment by iteles** [comment]
👍🏻

**Comment by nelsonic** [comment]
Using AWS SES as the free tier is 65k per month: https://aws.amazon.com/ses/pricing/
