### ISSUE TITLE
Use Riot to render templates so we can re-use tags from our site/app?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/sendemail#25]
Its great to *support* handlebars, but if we are going to use http://riotjs.com/ for our components in the app, does it make sense to re-use them when sending emails?

**Comment by nelsonic** [comment]
Lets "*solve*" this problem when the *need* arises... :wink:

**Comment by iteles** [comment]
👍🏻 Was going to say the same 😊

**Comment by nelsonic** [comment]
Using Handlebars for now. 👍
