### ISSUE TITLE
Google Apps Mail Sending Limits?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/sendemail#27]
<img width="598" alt="google-apps-email-sending-limits" src="https://cloud.githubusercontent.com/assets/194400/10867912/6de86f46-8073-11e5-8fa2-4b7a0c7ba02d.png">

https://support.google.com/a/answer/166852?hl=en

**Comment by SimonLab** [comment]
We need to monitor the free space of the elasticsearch database as it can reduce quickly!

**Comment by nelsonic** [comment]
yes... do you have an alert for this?

**Comment by nelsonic** [comment]
see: https://github.com/dwyl/sendemail-gmail/issues/2
