### ISSUE TITLE
Error when trying to send a test email

### ISSUE THREAD

**Issue by Conorc1000** [dwyl/sendemail#32]
I have attempted to set up sendemail 
https://github.com/OxfordAbstracts/application/tree/abb964f5ed020d8e65abd47e57e89a231ee575dc/src
but when I try to run my email.js file i get the following error, 
<img width="661" alt="screen shot 2016-05-04 at 14 56 12" src="https://cloud.githubusercontent.com/assets/12072531/15016326/664d2200-1208-11e6-8883-cfce891030f1.png">
Could this be because the the sendemail module is not able to find my config.env file?

**Comment by iteles** [comment]
Ah, the mandrill error may be more telling than you think in this @Conorc1000 as we're *replacing* Mandrill with SES

**Comment by nelsonic** [comment]
@Conorc1000 good question.  Which *version* of `sendemail` are you using?
see: https://github.com/dwyl/sendemail/blob/d5bdaa1f14fd8cf5a8ef9aae074963678c9dcab9/lib/index.js#L1

**Comment by Conorc1000** [comment]
"sendemail": "^1.0.9",

**Comment by nelsonic** [comment]
there's your problem... go with v.2.0.0 :wink:

**Comment by nelsonic** [comment]
@Conorc1000 are you still having issues sending email?
can you describe the steps you've gone through and/or link to the branch where your code is?

**Comment by Conorc1000** [comment]
Hi @nelsonic  yes changing the version of the module fixed the mandrill error. However now there is this error. 

![screen shot 2016-05-05 at 09 56 02](https://cloud.githubusercontent.com/assets/12072531/15039809/a2706a18-12a7-11e6-9dc4-680b9198bec5.png)

Here is the link to the branch 

https://github.com/OxfordAbstracts/application/tree/abb964f5ed020d8e65abd47e57e89a231ee575dc

I have set up my AWS account with SES, and the email address I am trying to send to is verified within the sand box environment. I have also had my account upgraded so that emails can be sent outside of the sandbox environment.

**Comment by nelsonic** [comment]
@Conorc1000 which email address is it complaining about?

**Comment by nelsonic** [comment]
I'd recommend you update to version `2.0.1` of `sendemail` and ensure you have the 
`SENDER_EMAIL_ADDRESS` environment variable set to an email address that you have verified.
see:https://github.com/dwyl/sendemail#2-set-your-environment-variables

**Comment by Conorc1000** [comment]
ok i've changed to v2.0.1 and ive added a sender email, my gmail account linked and verified on my AWS account. The problem now seems to be the file paths 
<img width="1217" alt="screen shot 2016-05-05 at 12 31 18" src="https://cloud.githubusercontent.com/assets/12072531/15042634/a484a1c8-12bd-11e6-81c0-30714cb6b216.png">

I cant seem to find a way of getting the right path to my templates. Could this be because im trying to just run the email.js file by itself 
```node /Users/conorcampbell/Documents/DWYL/application/src/sendEmail/email.js```
and not running the whole server?

**Comment by nelsonic** [comment]
Running the file by its' self should not cause you issues.

**Comment by Conorc1000** [comment]
The code works if I remove line 19 from index.js in the module.

![screen shot 2016-05-05 at 13 47 29](https://cloud.githubusercontent.com/assets/12072531/15043815/160513e6-12c8-11e6-9bcf-02b71c73e32b.png)

Is this a feasible fix?

**Comment by nelsonic** [comment]
@Conorc1000 sure, if that works for you and the tests still pass, please PR the change. 👍

**Comment by nelsonic** [comment]
@Conorc1000 still seeing this issue? (*if not please close...*)

**Comment by Conorc1000** [comment]
Yes Sendemail is working well
