### ISSUE TITLE
Email title is currently hardcoded as 'welcome to DWYL'

### ISSUE THREAD

**Issue by naazy** [dwyl/sendemail#38]
Surely this should be editable? Or have I misunderstood something?
https://github.com/dwyl/sendemail/blob/656d55d14302b6d9865ab707182975be7f66bb45/lib/index.js#L75-L77

**Comment by nelsonic** [comment]
@naazy please PR a fix in which the `person` parameter is changed to `params` and subject is passed in as `params.subject` . thanks! 👍
