### ISSUE TITLE
Testing of emails 

### ISSUE THREAD

**Issue by roryc89** [dwyl/sendemail#43]
At the moment email tests are simply checking that the data being passes to sendemail module (which uses SES) is as we expect and that there is no error in the sending of the email. But we are not testing if emails bounce and if they appear to the recipient as they should do.

Is this level of testing sufficient and are there ways to test the appearance and bouncing of emails?

**Comment by nelsonic** [comment]
There are *Two* things we can do to ensure that email functionality is working:

1. Setup an _inbound_ email address we can use to check the contents of email we send.
2. Setup a ["Cron"](https://en.wikipedia.org/wiki/Cron) (_regularly executed_) task to *reconcile* (check) the status of all emails we have sent and confirm if any bounced.

**Comment by nelsonic** [comment]
Example of setting up a Cron job using AWS Lambda: https://github.com/TheScienceMuseum/collectionsonline-sitemap

**Comment by nelsonic** [comment]
Hi @roryc89!
@shouston3 has _kindly_ updated the API of this package to be _easily_ testable.
We will need to _update_ our usage of it in OA. hopefully it's a small update. 
Please confirm this helps ... thanks! 👍

**Comment by roryc89** [comment]
Thanks for the update @nelsonic. I believe the update in OA was made a while ago. I don't think the level of e2e testing mentioned in the description as we can rely upon SES. Do you think we're ok to close this?

**Comment by nelsonic** [comment]
@roryc89 yeah, let's close it and re-open if we _need_ it. 👍
