### ISSUE TITLE
Implicit use of env2 in /lib/index.js

### ISSUE THREAD

**Issue by nelsonic** [dwyl/sendemail#44]
see: https://github.com/dwyl/sendemail/blob/471087f95dd1ac88186d4af21a3829546ec37fc9/lib/index.js#L1
We need to either _remove_ this or make it a `dependency` what are your thoughts @roryc89  ?

**Comment by roryc89** [comment]
Sorry just seen this now (lost in OA notifications!)

I don't have a strong opinion but... As I understand it this module is designed to help the user "to Get Started as Fast as Possible" and I think making the decision to use env2 helps with that. I think we should keep env2 and name it as a dependency.

**Comment by shouston3** [comment]
I'm not too sure about this, but I feel that sourcing your environment variables should be done once at the entry point to your application.

I'm not sure about re-sourcing them in an external library.

@nelsonic @roryc89 Would it be alright if I remove it and make it a dev dependency?

**Comment by nelsonic** [comment]
@shouston3 no objections to making `env2` a `devDependency`.
