### ISSUE TITLE
Suggest users to move out of sandbox env?

### ISSUE THREAD

**Issue by mk4111** [dwyl/sendemail#45]
Hi!
Might be a minor point, and slightly tangential to this npm module, but I was wondering if it might be helpful to users if, in the README.md, it's suggested that users move out of their sandbox environment (by requesting for an increase in sending quota for example), so that emails [can be sent to unregistered email addresses too](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html)? 
Please let me know what you think!
Thank you for an awesome module :)

**Comment by iteles** [comment]
@mk4111 That sounds great! Please add a sub-section with a paragraph explaining why you had to do this and how you did it to: https://github.com/dwyl/sendemail#which-email-service-provider if you have some time? 😊

**Comment by mk4111** [comment]
@iteles sorry for the delay - I'm on it now! :)

**Comment by mk4111** [comment]
Just made a PR [#48](https://github.com/dwyl/sendemail/pull/48) on this, hope it's ok!
