### ISSUE TITLE
Add note to readme on not using fake email addresses

### ISSUE THREAD

**Issue by iteles** [dwyl/sendemail#49]
When fake email addresses are used (i.e. for automated tests), it's incredibly easy to hit SES' limit of bounced emails and be blocked by the service.

I suggest we add a note to the readme to warn people of this.

**Comment by shouston3** [comment]
@iteles Another way to avoid this problem is to stub out emails being sent, doing so will mean you can have as many automated tests in your code as you like without worrying about hitting email limits.

(It will also drastically speed up your tests)

**Comment by shouston3** [comment]
I'm happy to write up a section about good practices for automated testing when using this as a third party library.

**Comment by otajor** [comment]
@shouston3 this would be super useful.
