### ISSUE TITLE
env2 devDependency can cause problems

### ISSUE THREAD

**Issue by franzmoro** [dwyl/sendemail#51]
### Description
As currently implemented, the lib/index.js requires 'env2', which does not get installed together with the "sendemail" module.

If the repo is using an env variable technique different from env2, then the sendEmail function will either crash or require a manual npm install of env2.

### Possible solutions
  - upgrade 'env2' to dependency (not just devDependency), or
  - do not require 'env2' on the lib/index.js, and instruct the developer(s) to just have the env variables already set up on the repo.

**Comment by nelsonic** [comment]
@franzmoro agreed. Please PR. thanks! 👍
