### ISSUE TITLE
Update devDependencies

### ISSUE THREAD

**Issue by iteles** [dwyl/sendemail#53]
Pretty sure that reading through the [relevant PR in decache](https://github.com/dwyl/decache/pull/23/files), this latest version is still backwards compatible, should be a quick update 👍 

https://david-dm.org/dwyl/sendemail?type=dev
<img width="1086" alt="screen shot 2016-12-30 at 22 44 04" src="https://cloud.githubusercontent.com/assets/4185328/21573876/e2356544-cee1-11e6-9657-ecfba7f89a61.png">

**Comment by shouston3** [comment]
Fixed by #54

**Comment by shouston3** [comment]
Fixed by #54
