### ISSUE TITLE
Being able to stub out the sendemail module

### ISSUE THREAD

**Issue by shouston3** [dwyl/sendemail#55]
When testing functions/endpoints that use `sendemail`, I would like to be able to stub out the `sendemail` function to avoid sending an actual email every time I run my tests (it slows down tests and fills up inboxes).

Libraries like sinon follow the pattern of `sinon.stub(module, 'methodToStub')`.

This module currently doesn't facilitate this pattern.

Would you consider changing the [api](https://github.com/dwyl/sendemail#4-send-an-email) to something like:

```
email.send('welcome', person, function (error, result) {
```

instead of:

```
email('welcome', person, function(error, result){
```

I'm happy to do this if you don't mind the api change

**Comment by nelsonic** [comment]
@shouston3 thank you for _creating_ this issue/question! 😻 
We have a _little_ experience using Sinon in [`aws-sdk-mock`](https://github.com/dwyl/aws-sdk-mock/blob/99fb51f3da657d593de7af523f5b6978c37fb518/package.json#L36) it might be worth _checking_ if this object-based method calling will work with Sinon before changing the API.

could you do the following:
 ```js
var email = require('sendemail').email;

email('welcome', person, function (error, result) {
// etc
}
``` 

> **BTW**: I'm **100% "On Board"** with _adding_ the default method to be the `email` one if that simplifies things but we _ideally shouldn't "break" backward compatibility for existing users of the module..._ 😉

**Comment by shouston3** [comment]
As far as I'm aware, you would only be able to overwrite methods of a required in object, not a required in function.
