### ISSUE TITLE
Allow CC and BCC

### ISSUE THREAD

**Issue by roryc89** [dwyl/sendemail#73]
sendemail currently doesn't allow sending of carbon copies or blind carbon copies. We should add options to allow this.

**Comment by nelsonic** [comment]
@roryc89 see: https://github.com/dwyl/sendemail/pull/65
please work with @amitmawkin to make this happen. 
thanks! ❤️  ✅  🚀

**Comment by roryc89** [comment]
@nelsonic on it! 👍

**Comment by iteles** [comment]
@roryc89 Can we close this issue based on PR #65 ? :)

**Comment by roryc89** [comment]
@iteles yes im closing this now
