### ISSUE TITLE
Users should be able to specify charset

### ISSUE THREAD

**Issue by roryc89** [dwyl/sendemail#76]
As a user of this library I would like to be able to specify the charset used in my body and subject. This would allow me to use `utf16` instead of `utf8` and avoid issues with non standard characters.

**Comment by iteles** [comment]
@roryc89 Could we default to `utf16` so this is never a question? Are there downsides?

**Comment by roryc89** [comment]
@iteles some people think so :
http://softwareengineering.stackexchange.com/questions/102205/should-utf-16-be-considered-harmful
http://utf8everywhere.org/

But I have a very limited understanding of this and I don't know if the issues mentioned in these sites apply to this context.

Perhaps best to keep defaulting to utf-8 for now?

**Comment by nelsonic** [comment]
@roryc89 new version published to NPM: `sendemail@3.3.0` thanks! 👍

**Comment by roryc89** [comment]
closing as implemented :)
