### ISSUE TITLE
Readme step 4 - duplicate function calls 

### ISSUE THREAD

**Issue by RobStallion** [dwyl/sendemail#85]
[Here](https://github.com/dwyl/sendemail/blame/master/README.md#L125) in the readme you call the function `sendemail.set_template_directory('path');` but it looks like this function is already being called in [here](https://github.com/dwyl/sendemail/blob/master/lib/index.js#L25) `lib/index.js`. 

Is this intentional?

**Comment by nelsonic** [comment]
@RobStallion I don't think it _is_ intentional. please feel free to fix/update. 👍
