### ISSUE TITLE
sending emails to multiple addresses

### ISSUE THREAD

**Issue by RobStallion** [dwyl/sendemail#86]
When trying to send an email to multiple email addresses at once I was getting an error.

It looks like [this line](https://github.com/dwyl/sendemail/blob/master/lib/index.js#L142) is putting the `toAddresses` into an array. This works if you just pass in one email address as a string but it does not work if you have multiple email addresses that you need to send to at once. 

I think that the person using the module should pass in an array to `toAddresses` themselves and the wrapping should be removed from the node module. This way we would not wrap an array within an array when sending to multiple email addresses. 

This is an example of an object that I am currently trying to call the `sendemail.email` function with
```
      var object = {
        toName: 'name',
        email: ['email1@email.com', 'email2@email.com'],
        subject: 'subject',
        details: 'details'
      };

      sendemail.email("template", object, function(error, result) {
        console.log(result);
      });
```

Is there another way that this function is intended to be used?

**Comment by nelsonic** [comment]
@RobStallion good question, thanks for opening this issue! 👍 
Hidden in the docs (Readme) is:
https://github.com/dwyl/sendemail#more-options
![image](https://user-images.githubusercontent.com/194400/37461990-44a8a98c-2848-11e8-916b-a4189c1d16f9.png)

Perhaps it's time for a "Table of Contents"...? 🤔

**Comment by shouston3** [comment]
@nelsonic @roryc89 what are your thoughts on catering for passing in `email` as an array of email strings:

```javascript
    var object = {
        toName: 'name',
        email: ['email1@email.com', 'email2@email.com'],
        subject: 'subject',
        details: 'details'
      };
```

and also catering for passing in a single `email` string:

```javascript
    var object = {
        toName: 'name',
        email: 'email1@email.com',
        subject: 'subject',
        details: 'details'
      };
```

**Comment by nelsonic** [comment]
@shouston3 / @RobStallion  / @parkhabit 
I'm happy with updating the `sendemail.email` to accept an `Array` on the `object.email`,
please write the necessary tests and (_if possible_) maintain backward compatibility.
There are a handful of people/projects using the module: https://www.npmjs.com/package/sendemail
![image](https://user-images.githubusercontent.com/194400/37539512-d3e45fb6-294b-11e8-9215-347fce449b51.png)

**Comment by shouston3** [comment]
Sounds good @nelsonic

**Comment by nelsonic** [comment]
`sendemail@3.4.0` on NPM includes @shouston3's update! 🎉  (_thanks again!_)
