### ISSUE TITLE
Hwo to send mail-log from webpage in S3 aws

### ISSUE THREAD

**Issue by autoprog** [dwyl/sendemail#99]
Hi, 
how to simple post send mail for my.
I tested CLI send-mail ok

now need code javascript on my page.

thanks,
Carlos.

**Comment by nelsonic** [comment]
Hi @autoprog, 👋 
What exactly are you trying to do?
Do you want to send an email from a static webpage hosted on S3?

**Comment by autoprog** [comment]
Hi,
I have S3 website static,
i need simple log send email to my mail.
I read doc,  not have simple system,  need lambda etc...

thanks,
Carlos.

**Comment by nelsonic** [comment]
@autoprog for this quest, I would recommend our sister project/tutorial: https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server if you don't want to have to run any backend.

**Comment by autoprog** [comment]
Hi, nelsonic,
thanks your link,
Carlos.
